export const Maps = [
  "Azagor",
  "Basra",
  "Construction",
  "District",
  "Dustydew",
  "Eduardovo",
  "Frugis",
  "Isle",
  "Lonovo",
  "MultuIslands",
  "Namak",
  "OilDunes",
  "Old_District",
  "Old_Eduardovo",
  "Old_MultuIslands", // need picture
  "Old_Namak",
  "Old_OilDunes", // need picture
  "River",
  "Salhan",
  "SandySunset",
  "TensaTown",
  "Valley",
  "VoxelLand",
  "Wakistan",
  "WineParadise",
];
